import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { getServerSession } from "next-auth";

import SessionProvider from "@/app/components/SessionProvider";

import NavMenu from "@/app/components/NavMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}> 
          <main className="mx-auto max-w-5xl text-2xl flex gap-2">
            <NavMenu />
            <div className="w-3/4 pt-12"> {children} </div>
          </main>
        </SessionProvider>
      </body>
    </html>
  );
}
